/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.chapter9;
/**
 *
 * @author Student
 */
public class Main extends javax.swing.JFrame {
    
    
      //Variables used to store extracted form details 
    Pizza myPizza;
    String wine = "";
    String pizzaBase ="";
    //toppings - not implemented here yet
    //extras - not implemented here yet 
    
    //Constants to represent the pizza base options 
    static final int NO_BASE_SELECTED = -1; 
    static final int PLEASE_SELECT = 0;
    static final int DEEP_DISH = 1;
    static final int GOURMET = 2; 
    static final int THIN_AND_CRISPY = 3; 
//    static final int BUBBLE_BASE = 4; 

    //Constants to represent the Extras options 
    static final int NO_EXTRA_SELECTED = -1; 
    static final int NONE = 0;
    static final int CHIPS = 1;
    static final int ONION_RINGS = 2; 
    static final int TACO_CHIPS = 3; 
    static final int WRAP = 4; 
    
    //Assume form is not completed at start
    //of program 
    static boolean formValidated =false; 
    
    //Method to Validate Form 
    private void validateForm()
    {
        //Check if pizza base selected
        //if not selected -> prompt
        //user to select pizza base 
        if(pizzaBaseCmb.getSelectedIndex()== NO_BASE_SELECTED
               || pizzaBaseCmb.getSelectedIndex()== PLEASE_SELECT )
       {
            JOptionPane.showMessageDialog(this, 
                "Please Select a Pizza Base!!",
                "Message Dialog", JOptionPane.WARNING_MESSAGE);
           
       }
        else {
            // Asumme form completed correctly 
            formValidated = true; 
        } 
        
    } //end validate form method 
    
    
    //Method to extract form details 
    private void extractForm()
    {
      //  local variable - not accessible
      // in the placeOrderBtn event handler
      //  String wine=""; 
        
        //Process Wine radio buttons
        if (redRadBtn.isSelected())
        {
            txtArea.setText("Red Wine Selected!");
            wine = "Red Wine";
        }
        
        else if (whiteRadBtn.isSelected())
        {
            txtArea.setText("White Wine Selected!");
            wine = "White Wine";
        }
        else
        {
            txtArea.setText("No Wine Selected!");
            wine = "No Wine";
        }
        
        
        boolean mushroom = false;
        boolean ham = false; 
        boolean pepperoni = false; 
        
//        
        //Process Check boxes
        if (mushroomChk.isSelected())
        {
            txtArea.append("\nMushroom topping selected");
            mushroom = true; 
        }
        if (hamChk.isSelected())
        {
            txtArea.append("\nHam topping selected");
            ham = true; 
        }
        if (pepperoniChk.isSelected())
        {
            txtArea.append("\nPepperoni topping selected");
            pepperoni = true; 
        }
        
      //  local variable - not accessible
      // in the placeOrderBtn event handler
      // String pizzaBase = "";
        
        
        //process pizza base combo box 
       if(pizzaBaseCmb.getSelectedIndex()== NO_BASE_SELECTED
               || pizzaBaseCmb.getSelectedIndex()== PLEASE_SELECT )
       {
            txtArea.append("\nPlease select Pizza base");
            pizzaBase = "No Pizza Base Selected";
       }
       else if (pizzaBaseCmb.getSelectedIndex()==DEEP_DISH) {
            txtArea.append("\nDeep Dish Base Selected");
            pizzaBase = "Deep Dish Base";
       }
       else if (pizzaBaseCmb.getSelectedIndex()==GOURMET) {
            txtArea.append("\nGourmet Base Selected");
            pizzaBase = "Gourmet Base";
       } 
       else if (pizzaBaseCmb.getSelectedIndex()==THIN_AND_CRISPY) {
            txtArea.append("\nThin & Crispy Base Selected");
            pizzaBase = "Thin & Crispy Base";
       }  
       
       //Process Extras List
       //to do
       
    } //end extract details form method 
    
    private void clearForm()
    {
        wineBtnGrp.clearSelection();
        
        //clear checkboxes
        mushroomChk.setSelected(false);
        pepperoni.setSelected(false);
        ham.setSelected(false);
        
        pizzaBaseCmb.setSelectedIndex(0);
        extrasList.clearSelection();
        
        txtArea.setText("");
        
    }
    


    /** Creates new form Main */
    public Main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        clearFormBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        whiteRadBtn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        redRadBtn = new javax.swing.JRadioButton();
        pepperoniChk = new javax.swing.JCheckBox();
        mushroomChk = new javax.swing.JCheckBox();
        hamChk = new javax.swing.JCheckBox();
        pizzaBaseCmb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        checkFormBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "None", "Chips", "Onion Rings", "Taco Chips", "Wrap" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        clearFormBtn.setText("Clear Form");
        clearFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFormBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Wine:");

        whiteRadBtn.setText("White");
        whiteRadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteRadBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Pizza Toppings:");

        redRadBtn.setText("Red");

        pepperoniChk.setText("Pepperoni");

        mushroomChk.setText("Mushroom");

        hamChk.setText("Ham");

        pizzaBaseCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Deep Dish", "Gourmet Style", "Thin & Crispy" }));

        jLabel1.setText("Pizza Base:");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jLabel2.setText("Extras:");

        checkFormBtn.setText("Place Order");
        checkFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFormBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(checkFormBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearFormBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(whiteRadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redRadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pizzaBaseCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mushroomChk, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pepperoniChk, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hamChk, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(whiteRadBtn)
                            .addComponent(pizzaBaseCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redRadBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hamChk)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mushroomChk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pepperoniChk))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkFormBtn)
                    .addComponent(clearFormBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFormBtnActionPerformed

        clearForm();

    }//GEN-LAST:event_clearFormBtnActionPerformed

    private void whiteRadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteRadBtnActionPerformed

    }//GEN-LAST:event_whiteRadBtnActionPerformed

    private void checkFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFormBtnActionPerformed

        //Clear the summary text area
        txtArea.setText("");

        //Validate form
        validateForm();

        //if form properly completed
        //process form i.e. extract form details
        if (formValidated)
        {
            extractForm();

            //Create Pizza
            //could also include toppings
            myPizza = new Pizza(pizzaBase);

            double pizzaPrice =  myPizza.calculatePrice();

            //update GUI with Pizza Price

            //Set number format to currency
            NumberFormat cf =
            NumberFormat.getCurrencyInstance();

            //  display price on form with euro sign
            //             priceLbl.setText(String.valueOf(cf.format(price)));

            txtArea.append("Pizza Price: "+ cf.format(pizzaPrice));

            //  reset form validation
            formValidated=false;

    }//GEN-LAST:event_checkFormBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(new Runnable() {
     //       public void run() {
                new Main().setVisible(true);
     //       }
      //  });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkFormBtn;
    private javax.swing.JButton clearFormBtn;
    private javax.swing.JCheckBox hamChk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox mushroomChk;
    private javax.swing.JCheckBox pepperoniChk;
    private javax.swing.JComboBox<String> pizzaBaseCmb;
    private javax.swing.JRadioButton redRadBtn;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JRadioButton whiteRadBtn;
    // End of variables declaration//GEN-END:variables

}
