/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.chapter9;

 
/**
 *
 * @author Student
 */
public class States extends javax.swing.JFrame {
    
//    final int NOT_SELECTED = -1
    final int DEEP_DISH = 0;
    final int GOURMET_STYLE = 1;
    final int THIN_AND_CRISPY = 2;
    
    
    public void resetFormInputs(){
        //reset inputs 
        //clear radio buttons
        wines.clearSelection();
        
        //clear check boxes 
        pepperoniChk.setSelected(false);
        mushroomChk.setSelected(false);
        
        //clear combo box
        box.setSelectedIndex(-1);   // -1 = Not Selected
    }

    /** Creates new form States */
    public States() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wines = new javax.swing.ButtonGroup();
        rad1 = new javax.swing.JRadioButton();
        rad2 = new javax.swing.JRadioButton();
        pepperoniChk = new javax.swing.JCheckBox();
        mushroomChk = new javax.swing.JCheckBox();
        box = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        checkFormBtn = new javax.swing.JButton();
        clearFormBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizza Order");

        wines.add(rad1);
        rad1.setText("White");
        rad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1ActionPerformed(evt);
            }
        });

        wines.add(rad2);
        rad2.setText("Red");

        pepperoniChk.setText("Pepperoni");

        mushroomChk.setText("Mushroom");

        box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deep Dish", "Gourmet Style", "Thin & Crispy" }));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        checkFormBtn.setText("Check Form");
        checkFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFormBtnActionPerformed(evt);
            }
        });

        clearFormBtn.setText("Clear Form");
        clearFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFormBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rad1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rad2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pepperoniChk, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mushroomChk, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(checkFormBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(clearFormBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad1)
                    .addComponent(rad2)
                    .addComponent(pepperoniChk)
                    .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mushroomChk)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkFormBtn)
                    .addComponent(clearFormBtn))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1ActionPerformed
   
        
        
    }//GEN-LAST:event_rad1ActionPerformed

    private void checkFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFormBtnActionPerformed
   
        // reset output 
        txtArea.setText("");

        //check form inputs and update output
        //Check the radio button - Update the Text Area 
        if (rad1.isSelected()){
            txtArea.append("White Wine Selected!\n");
        }
        else if (rad2.isSelected()){
            txtArea.append("Red Wine Selected!\n");
        }
               
        //Check the check boxes - Update the Text Area 
        if (pepperoniChk.isSelected()){
            txtArea.append("Pepperoni Topping Selected!\n");
        }
        
        if (mushroomChk.isSelected()){
            txtArea.append("Mushroom Topping Selected!\n");
        }
        
        //Check the combo box - Update the Text Area 
          //  Check what option is selected in the combo box 
        
        if (box.getSelectedIndex()==DEEP_DISH){
            //Deep Dish
            txtArea.append(box.getSelectedItem()+ " Selected\n");
        }
        else  if (box.getSelectedIndex()==GOURMET_STYLE){
            //Gourmet Style
            txtArea.append(box.getSelectedItem() +" Selected\n");
        }
        else  if (box.getSelectedIndex()==THIN_AND_CRISPY){
            //Thin & Crispy
            txtArea.append(box.getSelectedItem() +" Selected\n");
        }
       
        
        
        
        
    }//GEN-LAST:event_checkFormBtnActionPerformed

    
    
    
    
    
    private void clearFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFormBtnActionPerformed
        //reset form
        resetFormInputs();
    
        //reset ouptut
        txtArea.setText("");
    }//GEN-LAST:event_clearFormBtnActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(States.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(States.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(States.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(States.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(new Runnable() {
     //       public void run() {
                new States().setVisible(true);
     //       }
      //  });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box;
    private javax.swing.JButton checkFormBtn;
    private javax.swing.JButton clearFormBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mushroomChk;
    private javax.swing.JCheckBox pepperoniChk;
    private javax.swing.JRadioButton rad1;
    private javax.swing.JRadioButton rad2;
    private javax.swing.JTextArea txtArea;
    private javax.swing.ButtonGroup wines;
    // End of variables declaration//GEN-END:variables

}
